{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "C:\\Users\\jonas\\Documents\\epymarl\\epymarl\\src",
    "dependencies": [
      "munch==2.5.0",
      "numpy==1.24.3",
      "sacred==0.8.2",
      "torch==1.12.1"
    ],
    "mainfile": "main.py",
    "name": "pymarl",
    "repositories": [
      {
        "commit": "f355a55262ac9afecdb53368fec6337c549cc160",
        "dirty": true,
        "url": "https://github.com/uoe-agents/epymarl.git"
      },
      {
        "commit": "f355a55262ac9afecdb53368fec6337c549cc160",
        "dirty": true,
        "url": "https://github.com/uoe-agents/epymarl.git"
      },
      {
        "commit": "f355a55262ac9afecdb53368fec6337c549cc160",
        "dirty": true,
        "url": "https://github.com/uoe-agents/epymarl.git"
      }
    ],
    "sources": [
      [
        "main.py",
        "_sources\\main_59f46dede96070f41eb0bbace4ede0ce.py"
      ],
      [
        "run.py",
        "_sources\\run_fca7569cd3431950598e841e4242dc3e.py"
      ],
      [
        "utils\\logging.py",
        "_sources\\logging_7ddc698bb74674bae897bfdc5662ed00.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"C:\\Users\\jonas\\Documents\\epymarl\\epymarl\\src\\run.py\", line 38, in run\n    map_name = _config[\"env_args\"][\"map_name\"]\n",
    "KeyError: 'map_name'\n",
    "\nDuring handling of the above exception, another exception occurred:\n\n",
    "Traceback (most recent call last):\n",
    "  File \"C:\\Users\\jonas\\.conda\\envs\\pymarl\\lib\\site-packages\\sacred\\config\\captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"C:\\Users\\jonas\\Documents\\epymarl\\epymarl\\src\\main.py\", line 44, in my_main\n    run(_run, config, _log)\n",
    "  File \"C:\\Users\\jonas\\Documents\\epymarl\\epymarl\\src\\run.py\", line 40, in run\n    map_name = _config[\"env_args\"][\"key\"]\n",
    "KeyError: 'key'\n"
  ],
  "heartbeat": "2023-06-09T09:38:09.454953",
  "host": {
    "ENV": {},
    "cpu": "Unknown",
    "gpus": {
      "driver_version": "531.79",
      "gpus": [
        {
          "model": "NVIDIA GeForce GTX 960",
          "persistence_mode": false,
          "total_memory": 2048
        }
      ]
    },
    "hostname": "DESKTOP-1HDPUO6",
    "os": [
      "Windows",
      "Windows-10-10.0.22621-SP0"
    ],
    "python_version": "3.8.16"
  },
  "meta": {
    "command": "my_main",
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2023-06-09T09:38:08.975891",
  "status": "FAILED",
  "stop_time": "2023-06-09T09:38:09.458953"
}